# CONFIGURATION FILE
id = 1
project_dir = "C:\\Users\\fedes\\UNIPA\\MACHINE_LEARNING\\kc-predict\\data\\usarm_fede"

[make-data]
input_file = "data\\raw\\data_us_arm.csv"
output = "data\\"
visualize = false

[preprocess]
input = "data\\"
output = "data\\preprocessed"
features = ["DOY", "Tmin", "Tmax", "Tdew", "Uwind", "Vwind", "Rs"]
scaler = "MinMax"
folds = 2
k_seed = 241
visualize = false

[models.rf]
n_estimators = 1000
random_state = 42

# [models.mlp]
# hidden_layer_sizes = [100, 100, 100]
# max_iter = 1000
# random_state = 32652

# [models.knn]
# n_neighbors = 7
# weights = "distance"

[prediction]
input = "data\\preprocessed"
output = "data\\predictions"
visualize = true
