# CONFIGURATION FILE
# It is important that if ETo is not included in the features set,
# the raw data extracted in make-data are saved in an output folder named "data\\raw"
# as when creating kc series the ETo is searched automatically in that folder
id = 1
project_dir = "./us_arm_fede"

[make-data]
input_file = "us_arm_fede/data/data_us_arm.csv"
output_path = "data/raw"
visualize = false

[preprocess]
input_path = "data/raw"
output_path = "data/preprocessed"
features = ["DOY", "Tmin", "Tmax", "Tdew", "Uwind", "Vwind", "Rs"]
scaler = "MinMax"
folds = 2
k_seed = 241
visualize = false

# List all the models in the format [models.model_name],
# where model_name can be one of 'rf', 'mlp', 'knn'.
# List all the arguments required by the respective SciKit model
[models.rf]
n_estimators = 1000
random_state = 42

# [models.mlp]
# hidden_layer_sizes = [100, 100, 100]
# max_iter = 1000
# random_state = 32652

# [models.knn]
# n_neighbors = 7
# weights = "distance"

[prediction]
input_path = "data/preprocessed"
output_path = "data/predictions"
visualize = false

[postprocess]
input_path = "data/predictions"
output_path = "data/postprocessed"
# The Allen Trapezoidal file must have a first column called 'Day' and one 'Allen' column
<<<<<<< Updated upstream
trapezoidal_path = "data/external/trapezoidal_us_arm.csv"
reference_series = "Allen"
=======
trapezoidal_path = "us_arm_fede/data/trapezoidal_us_arm.csv"
>>>>>>> Stashed changes
contamination = 0.01
seed = 42
visualize = true
